Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,5 @@
 name: CI
+
 on:
   push:
     branches:
@@ -6,22 +7,33 @@ on:
 
 jobs:
   flutter_test:
-    name: Run flutter test and analyze
+    name: Run Flutter Test and Analyze
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
       - uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - uses: subosito/flutter-action@v1
+      - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
 
       - run: flutter pub get
-      - run: flutter analyze
+
+      - name: Analyze Code (fail only on errors)
+        run: |
+          flutter analyze > analysis.log
+          cat analysis.log
+          if grep -q "error •" analysis.log; then
+            echo "❌ Found errors in flutter analyze"
+            exit 1
+          else
+            echo "✅ No errors found"
+          fi
+
       - run: flutter test
 
 
@@ -30,27 +42,36 @@ jobs:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v4
+
       - uses: actions/setup-java@v3
         with:
-          java-version: "17"
+          java-version: '17'
+          distribution: 'temurin'
+
       - uses: subosito/flutter-action@v2
         with:
-          channel: "stable"
+          channel: 'stable'
+
       - run: flutter pub get
       - run: flutter clean
       - run: flutter build ios --release --no-codesign
+
 
   build_appbundle:
     name: Build Flutter (Android)
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - uses: actions/setup-java@v3
         with:
-          java-version: "17"
+          java-version: '17'
+          distribution: 'temurin'
+
       - uses: subosito/flutter-action@v2
         with:
-          channel: "stable"
+          channel: 'stable'
+
       - run: flutter pub get
       - run: flutter clean
       - run: flutter build appbundle
